spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/movie_theater
        username: root
        password: 123456
    security:
      oauth2:
        client:
            registration:
                google:
                    client-id: 594756081877-lfiu7p9vtj9vptbdbvdllqfk0gdhd09s.apps.googleusercontent.com
                    client-secret: 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
                    scope: openid,profile,email
        resourceserver:
          jwt:
              issuer-uri: https://accounts.google.com
              jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs


